Controllers/AboutUsController.cs
using EgiantsService;
using EgiantsWebsite.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EgiantsWebsite.Controllers
{
    public class AboutUsController : Controller
    {
        private readonly IAboutUsService _aboutUsService;
        public AboutUsController(IAboutUsService aboutUsService)
        {
            _aboutUsService = aboutUsService;
        }
        public ActionResult AllAboutUs()
        {
            var contacts = _aboutUsService.AllAboutUs();
            var aboutUsApplicationViewModel = new AboutUsApplicationViewModel
            {
                AboutUsList = contacts
            };
            return View(aboutUsApplicationViewModel);

        }
        // GET: AboutUs
        public ActionResult AboutUs()
        {
            return View();
        }
    }
}

Controllers/CareerController.cs
using EgiantsService;
using EgiantsWebsite.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EgiantsWebsite.Controllers
{
    public class CareerController : Controller
    {
        private readonly ICareerService _careerService;
        public CareerController(ICareerService careerService)
        {
            _careerService = careerService;
        }
        public ActionResult AllCareers()
        {
            var contacts = _careerService.AllCareers();
            var careerApplicationViewModel = new CareerApplicationViewModel
            {
                ContactsList = contacts
            };
            return View(careerApplicationViewModel);

        }
        // GET: Career
        public ActionResult Career()
        {
            return View();
        }
    }
}

Controllers/ClientController.cs
using EgiantsService;
using EgiantsWebsite.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EgiantsWebsite.Controllers
{
    public class ClientController : Controller
    {
        private readonly IClientService _clientService;
        public ClientController(IClientService clientService)
        {
            _clientService = clientService;
        }
        public ActionResult AllClients()
        {
            var contacts = _clientService.AllClients();
            var clientApplicationViewModel = new ClientApplicationViewModel
            {
                ContactsList = contacts
            };
            return View(clientApplicationViewModel);
        }

        // GET: Client
        public ActionResult Client()
        {
            return View();
        }
    }
}

Controllers/ContactController.cs
using EgiantsWebsite.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EgiantsService;
using AutoMapper;

namespace EgiantsWebsite.Controllers
{
    public class ContactController : Controller
    {
        private readonly IApplicationService _applicationService;
        public ContactController(IApplicationService applicationService)
        {
            _applicationService = applicationService;      
        }
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetAllContacts()
        {
            var contacts = _applicationService.GetAllContacts();
            var contactApplicationViewModel = new ContactApplicationViewModel
            {
                ContactsList = contacts
            };
            return View(contactApplicationViewModel);
            
        }
        [HttpGet]
        public ActionResult Contact()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Contact(ContactViewModel viewModel)
        {
            if(ModelState.IsValid)
            {
                //Map viewModel to Dto
                var contactDto=Mapper.Map<ContactViewModel,ContactDto>(viewModel);
                //Save the Contact to DataBase
                _applicationService.AddContact(contactDto);
                return RedirectToAction("GetAllContacts");
            }
            return View(viewModel);
        }
       
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">About Us<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("About Us", "AboutUs", "AboutUs")</li>
                            <li>@Html.ActionLink("Get All About Us", "AllAboutUs", "AboutUs")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Services<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Services", "Service", "Service")</li>
                            <li>@Html.ActionLink("Get All Services", "AllServices", "Service")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Clients<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Clients", "Client", "Client")</li>
                            <li>@Html.ActionLink("Get All Clients", "AllClients", "Client")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Careers<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Careers", "Career", "Career")</li>
                            <li>@Html.ActionLink("Get All Careers", "AllCareers", "Career")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Contact Administration<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Contact Us", "Contact", "Contact")</li>
                            <li>@Html.ActionLink("Get All Contacts","GetAllContacts","Contact")</li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>